export const products = [
  {
    id: 1,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 2,
    name: "Classic Denim Jacket",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹149",
    originalPrice: "Rs. 799₹",
    rating: 4.5,
    reviewCount: 92,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKcBfU1sxyXgMhpt9AIVKOIS08lD1u9Do9YiIxchw04pSH1vN5c4-tDq69yN-wav_9i0&usqp=CAU",
    imageAlt: "Denim jacket with button closure and front pockets.",
    color: "black",
    colors: [
      { name: "Blue", class: "bg-blue-500", selectedClass: "ring-blue-500" },
      { name: "Black", class: "bg-black", selectedClass: "ring-black" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
    ],
  },

  {
    id: 3,
    name: "Pep Jeans",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹299",
    originalPrice: "Rs. 799₹",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/C10636.jpg?im=Resize,width=350",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 4,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },

  {
    id: 5,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 6,
    name: "Classic Denim Jacket",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹149",
    originalPrice: "Rs. 799₹",
    rating: 4.5,
    reviewCount: 92,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKcBfU1sxyXgMhpt9AIVKOIS08lD1u9Do9YiIxchw04pSH1vN5c4-tDq69yN-wav_9i0&usqp=CAU",
    imageAlt: "Denim jacket with button closure and front pockets.",
    color: "black",
    colors: [
      { name: "Blue", class: "bg-blue-500", selectedClass: "ring-blue-500" },
      { name: "Black", class: "bg-black", selectedClass: "ring-black" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
    ],
  },

  {
    id: 7,
    name: "Pep Jeans",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹299",
    originalPrice: "Rs. 799₹",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/C10636.jpg?im=Resize,width=350",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 8,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },

  {
    id: 9,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 10,
    name: "Classic Denim Jacket",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹149",
    originalPrice: "Rs. 799₹",
    rating: 4.5,
    reviewCount: 92,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKcBfU1sxyXgMhpt9AIVKOIS08lD1u9Do9YiIxchw04pSH1vN5c4-tDq69yN-wav_9i0&usqp=CAU",
    imageAlt: "Denim jacket with button closure and front pockets.",
    color: "black",
    colors: [
      { name: "Blue", class: "bg-blue-500", selectedClass: "ring-blue-500" },
      { name: "Black", class: "bg-black", selectedClass: "ring-black" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
    ],
  },

  {
    id: 11,
    name: "Pep Jeans",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹299",
    originalPrice: "Rs. 799₹",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/C10636.jpg?im=Resize,width=350",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 12,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
];
