export const products = [
  {
    id: 1,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 2,
    name: "Classic Denim Jacket",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹149",
    originalPrice: "Rs. 799₹",
    rating: 4.5,
    reviewCount: 92,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKcBfU1sxyXgMhpt9AIVKOIS08lD1u9Do9YiIxchw04pSH1vN5c4-tDq69yN-wav_9i0&usqp=CAU",
    imageAlt: "Denim jacket with button closure and front pockets.",
    color: "black",
    colors: [
      { name: "Blue", class: "bg-blue-500", selectedClass: "ring-blue-500" },
      { name: "Black", class: "bg-black", selectedClass: "ring-black" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
    ],
  },

  {
    id: 3,
    name: "Aero Armar",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹199",
    originalPrice: "Rs. 799₹",
    rating: 3.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6W4PrFIrvlLB6ISMO-Tiax6RyxLHpld0ALCz7Jfxx6BfVmC9yxpjIQON6fSwZD0-Dik&usqp=CAU",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 4,
    name: "Pep Jeans",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹299",
    originalPrice: "Rs. 799₹",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/C10636.jpg?im=Resize,width=350",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },
  {
    id: 5,
    name: "Go Devil",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹199",
    originalPrice: "Rs. 799₹",
    rating: 1.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://images.stylight.net/image/upload/t_web_product_330x440max_nobg/q_auto:eco,f_auto/fhwmkhnmjksqnudfeboq.webp",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },
  {
    id: 6,
    name: "Basic 6-Pack",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹300",
    originalPrice: "Rs. 799₹",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 7,
    name: "Printed Cotton",
    decscription: "Men Solid  Printed cotton",
    offerPrice: "RS. ₹399",
    originalPrice: "Rs. 999₹",
    rating: 4.9,
    reviewCount: 1171,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWg9IWuePkfskmf0y0_xaMtiLx5lwsyURjDA&s",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
      { name: "red", class: "bg-red-600", selectedClass: "ring-red-600" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },

  {
    id: 8,
    name: "Marvel",
    decscription: "Men Solid  Marvel cotton",
    offerPrice: "RS. ₹799",
    originalPrice: "Rs. 1799₹",
    rating: 4.9,
    reviewCount: 1922,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbswbk9m9-6KQQlLzrSx-qWifTV8OyX2jRbw&s",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "Blue",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-900" },
      { name: "Blue", class: "bg-blue-900", selectedClass: "ring-blue-900" },
      {
        name: "Sky Blue",
        class: "bg-skyblue-300",
        selectedClass: "ring-skyblue-300",
      },
      { name: "Pink", class: "bg-pink-600", selectedClass: "ring-pink-600" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },

  {
    id: 9,
    name: "Printed Cotton",
    decscription: "Men Solid  Printed cotton",
    offerPrice: "RS. ₹399",
    originalPrice: "Rs. 999₹",
    rating: 4.9,
    reviewCount: 1171,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWg9IWuePkfskmf0y0_xaMtiLx5lwsyURjDA&s",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
      { name: "red", class: "bg-red-600", selectedClass: "ring-red-600" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 10,
    name: "Printed Cotton",
    decscription: "Men Solid  Printed cotton",
    offerPrice: "RS. ₹399",
    originalPrice: "Rs. 999₹",
    rating: 4.9,
    reviewCount: 1171,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWg9IWuePkfskmf0y0_xaMtiLx5lwsyURjDA&s",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
      { name: "red", class: "bg-red-600", selectedClass: "ring-red-600" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },

  {
    id: 11,
    name: "Basic Tee",
    decscription: "Men Solid  cotton",
    offerPrice: "RS. ₹192",
    originalPrice: "Rs. 799₹",
    rating: 2.9,
    reviewCount: "117",
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    color: "black",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
];
