export const products = [
  {
    id: 1,
    name: "Basic Tee 6-Pack",
    price: "$192",
    rating: 2.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: true },
    ],
  },
  {
    id: 2,
    name: "Classic Denim Jacket",
    price: "$120",
    rating: 4.5,
    reviewCount: 92,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKcBfU1sxyXgMhpt9AIVKOIS08lD1u9Do9YiIxchw04pSH1vN5c4-tDq69yN-wav_9i0&usqp=CAU",
    imageAlt: "Denim jacket with button closure and front pockets.",
    colors: [
      { name: "Blue", class: "bg-blue-500", selectedClass: "ring-blue-500" },
      { name: "Black", class: "bg-black", selectedClass: "ring-black" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
    ],
  },

  {
    id: 1,
    name: "Basic Tee 6-Pack",
    price: "$192",
    rating: 3.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN6W4PrFIrvlLB6ISMO-Tiax6RyxLHpld0ALCz7Jfxx6BfVmC9yxpjIQON6fSwZD0-Dik&usqp=CAU",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },

  {
    id: 1,
    name: "Basic Tee 6-Pack",
    price: "$192",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/C10636.jpg?im=Resize,width=350",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },
  {
    id: 1,
    name: "Basic Tee 6-Pack",
    price: "$192",
    rating: 1.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://images.stylight.net/image/upload/t_web_product_330x440max_nobg/q_auto:eco,f_auto/fhwmkhnmjksqnudfeboq.webp",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },
  {
    id: 1,
    name: "Basic Tee 6-Pack",
    price: "$192",
    rating: 4.9,
    reviewCount: 117,
    href: "#",
    imageSrc:
      "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg",
    imageAlt: "Two each of gray, white, and black shirts arranged on table.",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
      { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
      { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
    ],
    sizes: [
      { name: "XXS", inStock: true },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
      { name: "XXXL", inStock: false },
    ],
  },
];
